# The API for Cloud Run. Built from the repo root on purpose: api/ imports ../contracts/py and
# reads ../eval/runs for the PRISM screen's run history, so the image keeps that layout.
#
#   gcloud run deploy ledgersentinel-api --source . --region asia-south1 \
#     --allow-unauthenticated --env-vars-file deploy/cloudrun.env.yaml
#
# Secrets are NOT in this image: they arrive as env vars at deploy time from a gitignored
# file generated by deploy/make_cloudrun_env.py. MODELS_MOCK=true - the model service needs
# a GPU and the mock path is the measured demo path.

FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1

WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY contracts/ ./contracts/
COPY eval/runs/ ./eval/runs/
COPY api/ ./api/

# Cloud Run sets PORT; default for local `docker run`.
ENV PORT=8080
EXPOSE 8080
CMD exec uvicorn main:app --app-dir api --host 0.0.0.0 --port ${PORT}
