"""Generate deploy/cloudrun.env.yaml from api/.env for `gcloud run deploy --env-vars-file`.

    python deploy/make_cloudrun_env.py
    gcloud run deploy ledgersentinel-api --source . --region asia-south1 \
        --allow-unauthenticated --env-vars-file deploy/cloudrun.env.yaml --project ledgersentinel-hq

The output carries the Supabase service key and the PRISM key. It is gitignored; never commit
it. Cloud Run keeps the values in the service revision, which is where secrets belong for a
deployment that has no Secret Manager budget - and they can be rotated with one redeploy.
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ENV = ROOT / "api" / ".env"
OUT = ROOT / "deploy" / "cloudrun.env.yaml"

COPY = (
    "SUPABASE_URL",
    "SUPABASE_ANON_KEY",
    "SUPABASE_SERVICE_KEY",
    "PRISMTRACE_API_KEY",
    "PRISMTRACE_PROJECT_ID",
    "PRISMTRACE_HOST",
)
FIXED = {
    "MODELS_MOCK": "true",  # the model service needs a GPU; the deployed API serves fixtures
    "WEB_ORIGIN": "https://ledgersentinel-hq.web.app",
}


def main() -> int:
    if not ENV.exists():
        sys.exit(f"{ENV} not found - the deploy needs the real keys")
    env: dict[str, str] = {}
    for line in ENV.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    missing = [k for k in COPY if not env.get(k)]
    if missing:
        sys.exit(f"api/.env is missing: {', '.join(missing)}")

    lines = ["# GENERATED by deploy/make_cloudrun_env.py from api/.env. CONTAINS SECRETS. GITIGNORED."]
    lines += [f'{k}: "{v}"' for k, v in FIXED.items()]
    lines += [f'{k}: "{env[k]}"' for k in COPY]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(COPY)} secrets + {len(FIXED)} fixed). Gitignored - verify with `git status`.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
