#!/usr/bin/env python3
"""Generate db/seed.sql from the 8 scenario fixtures.

    python db/seed_from_fixtures.py > db/seed.sql

Generated rather than hand-written so the database seed and the PRISM cohort cannot drift apart.
Add a scenario to contracts/fixtures/ and re-run; the seed follows.

Every row here is synthetic (rule 10). There is no real customer, no real account, no real
transaction, and no real message anywhere in it.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "contracts" / "fixtures"

# Which channel each communication id belongs to. The fixtures describe calls and messages;
# this maps them so the consent policy has something real to gate on.
CHANNEL = {
    "comm_771": "call", "comm_772": "sms", "comm_805": "sms",
    "comm_910": "chat", "comm_911": "chat", "comm_1020": "call",
    "comm_1140": "email", "comm_1255": "email", "comm_1256": "call",
    "comm_1380": "sms", "comm_1490": "sms",
}


def q(v) -> str:
    """Quote a value for SQL."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, tuple)):
        if not v:
            return "'{}'"
        inner = ",".join(str(x).replace('"', '\\"') for x in v)
        return "'{" + inner + "}'"
    return "'" + str(v).replace("'", "''") + "'"


def main() -> int:
    out: list[str] = [
        "-- GENERATED by db/seed_from_fixtures.py - do not edit by hand.",
        "-- Re-run after changing contracts/fixtures/.",
        "-- All data is synthetic (rule 10).",
        "",
        "begin;",
        "",
    ]

    customers, accounts, comms, consents = {}, {}, {}, set()

    for path in sorted(FIXTURES.glob("*.json")):
        fx = json.loads(path.read_text(encoding="utf-8"))
        sid = fx["scenario_id"]
        txn, cust = fx["transaction"], fx["customer"]
        cid = cust["customer_id"]

        customers[cid] = cust
        accounts[txn["account_id"]] = (txn["account_id"], cid)

        out.append(f"-- ===== {sid}: {fx['expected_action']} =====")

        for comm_id in txn.get("communication_ids", []):
            ch = CHANNEL.get(comm_id, "sms")
            quote = next(
                (s.get("redacted_quote") for s in fx["signals"]
                 if s["source_ref"] == comm_id and s.get("redacted_quote")),
                None,
            )
            comms[comm_id] = (comm_id, cid, ch, txn["timestamp"], quote)
            consents.add((cid, ch))

        # transaction
        out.append(
            "insert into transactions (transaction_id, account_id, customer_id, amount, currency,"
            " destination_country, destination_ref, occurred_at, location, device,"
            " first_time_beneficiary) values ("
            + ", ".join([
                q(txn["transaction_id"]), q(txn["account_id"]), q(cid), q(txn["amount"]),
                q(txn["currency"]), q(txn.get("destination_country")),
                q(txn.get("destination_ref")), q(txn["timestamp"]), q(txn.get("location")),
                q(txn.get("device")),
                q(txn.get("destination_ref", "") == "benef_first_seen"),
            ])
            + ") on conflict do nothing;"
        )

        for e in fx["evidence"]:
            out.append(
                "insert into evidence (evidence_id, source_type, source_ref, claim, confidence,"
                " occurred_at, signal_refs, redacted_quote, critical) values ("
                + ", ".join([
                    q(e["evidence_id"]), q(e["source_type"]), q(e["source_ref"]), q(e["claim"]),
                    q(e["confidence"]), q(e["timestamp"]), q(e.get("signal_refs", [])),
                    q(e.get("redacted_quote")), q(e.get("critical", False)),
                ])
                + ") on conflict do nothing;"
            )

        a = fx["assessment"]
        out.append(
            "insert into assessments (assessment_id, transaction_id, risk_score, confidence,"
            " factors, evidence_ids, identity_assurance, critical_evidence_present, degraded,"
            " model_version) values ("
            + ", ".join([
                q(a["assessment_id"]), q(a["transaction_id"]), q(a["risk_score"]),
                q(a["confidence"]), q(a["factors"]), q(a.get("evidence_ids", [])),
                q(a.get("identity_assurance")), q(a.get("critical_evidence_present", False)),
                q(a.get("degraded", False)), q(a["model_version"]),
            ])
            + ") on conflict do nothing;"
        )

        d = fx["decision"]
        out.append(
            "insert into decisions (decision_id, transaction_id, assessment_id, action,"
            " human_required, policy_version, rationale_refs, trace_id, proposal_rejected,"
            " cool_off_seconds, hold_expires_at, verification_channel) values ("
            + ", ".join([
                q(d["decision_id"]), q(d["transaction_id"]), q(d.get("assessment_id")),
                q(d["action"]), q(d["human_required"]), q(d["policy_version"]),
                q(d["rationale_refs"]), q(d["trace_id"]), q(d.get("proposal_rejected", False)),
                q(d.get("cool_off_seconds")), q(d.get("hold_expires_at")),
                q(d.get("verification_channel")),
            ])
            + ") on conflict do nothing;"
        )

        # A case for anything that stopped the transaction.
        if d["action"] in ("HOLD", "ESCALATE", "COOL_OFF"):
            out.append(
                "insert into cases (case_id, transaction_id, decision_id, status) values ("
                + ", ".join([
                    q(f"case_{sid.lower()}"), q(d["transaction_id"]), q(d["decision_id"]),
                    q("open"),
                ])
                + ") on conflict do nothing;"
            )
        out.append("")

    # Parents first, so insert them ahead of everything above.
    head: list[str] = ["-- customers, accounts, communications, consent", ""]
    for cid, c in sorted(customers.items()):
        head.append(
            "insert into customers (customer_id, age_band, account_age_days,"
            " identity_assurance, normal_activity) values ("
            + ", ".join([
                q(cid), q(c.get("age_band")), q(c.get("account_age_days")),
                q(c.get("identity_assurance", "BASIC")), q(c.get("normal_activity")),
            ])
            + ") on conflict do nothing;"
        )
    for aid, (account_id, cid) in sorted(accounts.items()):
        head.append(
            f"insert into accounts (account_id, customer_id) values ({q(account_id)}, {q(cid)})"
            " on conflict do nothing;"
        )
    for comm_id, (cid_, customer_id, ch, ts, quote) in sorted(comms.items()):
        head.append(
            "insert into communications (communication_id, customer_id, channel, occurred_at,"
            " redacted_excerpt, redaction_applied) values ("
            + ", ".join([q(cid_), q(customer_id), q(ch), q(ts), q(quote), q(["BANK", "NAME"])])
            + ") on conflict do nothing;"
        )
    head.append("")
    for customer_id, ch in sorted(consents):
        head.append(
            "insert into consents (customer_id, channel, granted, granted_at) values ("
            + ", ".join([q(customer_id), q(ch), "true", "now()"])
            + ") on conflict do nothing;"
        )
    head.append("")

    out = out[:6] + head + out[6:] + ["commit;", ""]
    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
